{% set name = "superlu" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xiaoyeli/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3e464afa77335de200aeb739074a11e96d9bef6d0b519950cfa6684c4be1f350

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - openblas {{ openblas }} 
  run:
    - libopenblas 

test:
  commands:
    - test -f ${PREFIX}/lib/libsuperlu${SHLIB_EXT}
    - test -f ${PREFIX}/include/slu_ddefs.h
    - test -f ${PREFIX}/include/slu_sdefs.h
    - test -f ${PREFIX}/include/slu_zdefs.h
    - test -f ${PREFIX}/include/slu_dcomplex.h
    - test -f ${PREFIX}/include/slu_scomplex.h
    - test -f ${PREFIX}/include/slu_util.h
    - test -f ${PREFIX}/include/superlu_enum_consts.h

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: BSD-3-Clause
  license_file: License.txt
  summary: |
    Supernodal LU: solvers for large, sparse, nonsymmetric systems of linear
    equations.
  description: | 
    SuperLU contains a set of subroutines to solve a sparse linear system A*X=B. It uses 
    Gaussian elimination with partial pivoting (GEPP). The columns of A may be preordered 
    before factorization; the preordering for sparsity is completely separate from the factorization.

extra:
  recipe-maintainers:
    - grlee77
    - MWaszkiewicz-Anaconda
