appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nXF3sphvRH4vFU+maBaeUIjDP4VFpnTH0cOnmo/i6/gDCZDQOHXAAKOKMJwKuoy+mhoNa1vr1GM5RelemHj4odCCi3sPYSWH+FaA73EmUJBB2eeyjbH/ry4mS7CLJ2D2DdrNl+ITtcXQoc/imN0Wi3JxCbE6kdUKNxxKrXfhh8iW21hYeravLh4wfUL6gkN1TN59FVV2iHltKVc/dViZWrJ90AtXeAomAhbVXjijm7AAY+C0Y/ad0uQ8Aym5ATF/AwHKduMeYj9WFywZ6sTkrxZMrhLWvBclW+gf2Yc24PqKfcPfPKIepnBI+7S9emxdeIv+Gf9XxGQ+GWFKOeWkqROw1G3lHPxuOzXdDXjdqwJd/ufV04U/DvNPQXORKhy8Fw/Utm0Zlyd/lYqKDMQJTWnEzW6E2hu9DGfsW/rM63HI/xV3lpr+C2o7xz1b3d2tjaT1w/gIGQrX0pXFA67b0eLLR5N4/W1hQbXvoa5/Pykt8lQ0V2krAgTIh9++C20Twe+gMQxzONMbNJlzdj4V7+GtyIHO2s3fFjhrpiuvXm2XYexnkc+fhkduMspT982/Lo/QWrQGpg+izFZvc8hQQyy/JVbm9DNbVxWaGqB+j6AwHUaRk/xYGyMeBviOKrwsTWSqBH4mefiSpYFOEN6xhtrwtCoR75WBavMwx3v42Ow=}
