travis:
  secure:
    BINSTAR_TOKEN: Gn56x0DZnJzxqbnDmL40aZCa3TeDd71pkcGuhWg7YkIbgJjJUQdI66sa0FfctqJbH5ra7HLvTDug/OwxQhlCpHjCrtdJ4NxIR2Jbpd8KyGLggRH6JDs6e4Ak34hKqf+MWxaeFBQOW3qoj6Jn3vCbIKx8XLK6aUmhT9OIPwnyVaZKHQ1LRk1WFvavtefyYV8ZmO3G+v3trGXBFXuBVYyRgmYpUGR6DI8DEr85yNjoSwUPtGnagVmrT6Za+Aan3oH3+Ou/OE0FvibJMx+wv8G2ZVPVT3EootvewnGG9jUNHhtL7jtyigtw/6IUSWetzC770bbzlnmLcSPtwIYh+rCUgfgLAvNz/+KWgg1frz4h90/Rt6gzhg9mScb+gs77VnPdjbru7hIUYwqycJ2mGyhCmk4vQG4ueWbSjEUvjt5D1NRBnM+8h8lo+ssMzr3B+3VvyR1dvfO1SL9yyEZYYuCzT5agtrL9RGcBOSkhA7H8+K6WltFBmcoQDrT3h0uoNy+IajT9OI7M5HXURY87+0PumxibKOceIaoRQABSTBiqzjCHkhdr15ML6d4rMis4tTrthwfXA8/668cFTTfA3dB1TPANFwmNhxnfRub4di2BQJxXBc2NrKlgr9miLrd7dhcUbF0svXfgfAa8ZJI8fym2wAzdnfbVUihVvU9+BrLqbzw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
